/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package convexhull;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;
import java.awt.geom.Path2D;
import java.awt.geom.Point2D;
import javax.swing.BorderFactory;

/**
 *
 * @author jethro
 */
public class drawPanel extends javax.swing.JPanel {

    protected Point2D [] point;
    protected Path2D poly;
    protected Point2D [] recpt;
    protected Path2D rec;
    
    public drawPanel() {
        point = new Point2D[0]; 
        poly = new Path2D.Double();
        recpt = new Point2D [0]; 
        rec = new Path2D.Double();
        initComponents();
        setBorder(BorderFactory.createLineBorder(Color.black));
        setBackground(Color.white);
    }
    
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        Graphics2D gfx = (Graphics2D)g;
                
        int width = this.getWidth();
        int height = this.getHeight();
        
        if(point.length != 0){
            for (int i = 0;i<point.length;i++){
                int x = (int) (point[i].getX()*width);
                int y = (int) ((1-point[i].getY())*height);
                gfx.drawLine(x-5,y-5,x+5,y+5);
                gfx.drawLine(x-5,y+5,x+5,y-5);

            }
        }
        gfx.setColor(Color.RED);
        AffineTransform at = AffineTransform.getScaleInstance(width,-height);
        poly.transform(at);
        at = AffineTransform.getTranslateInstance(0, height);
        poly.transform(at);
        gfx.draw(poly);
        
        gfx.setColor(Color.BLUE);
        AffineTransform bt = AffineTransform.getScaleInstance(width,-height);
        rec.transform(bt);
        bt = AffineTransform.getTranslateInstance(0, height);
        rec.transform(bt);
        gfx.draw(rec);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
